name: Node CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: js-cli/package-lock.json
      - name: Install deps
        run: |
          cd js-cli
          npm ci || npm i
      - name: Lint
        run: |
          cd js-cli
          npm run lint --if-present || echo "no lint script"
      - name: Test
        run: |
          cd js-cli
          npm test --if-present || echo "no tests"
